Drupal parsing
usagov/usagov-logshipper pull request #3
Opened 2023-12-08 18:29 UTC by jacobaaronyeager

2023-12-09 01:06 UTC, akf requested changes
I noted a couple of files to delete and a function I'd like to see renamed.

2023-12-09 01:06 UTC, akf commented on project_conf/scripts/parse_drupal_keys.lua
> +    print("record: ")
Remove print statements

2023-12-09 01:06 UTC, akf commented on project_conf/scripts/parse_http_headers.lua
> +-- Convert the http_headers field (block of text) to a table of key:value pairs
Remove this file (duplicate of the one in cg-logshipper/scripts)

2023-12-09 01:06 UTC, akf commented on project_conf/scripts/parse_keys_with_eq_pairs.lua
> +-- This parser is just a proof-of-concept.
Remove this file (duplicate of the one in cg-logshipper/scripts, but with print statements).

2023-12-12 20:41 UTC, jacobaaronyeager commented
@akf Updated

2023-12-14 22:54 UTC, akf approved these changes

2023-12-14 22:54 UTC, merged